DROP TABLE IMG_FILE;
DROP TABLE BOARD_COMMENT;
DROP TABLE BOARD;
DROP TABLE REVIEW;
DROP TABLE HEART;
DROP TABLE ALERT;
DROP TABLE MENU;
DROP TABLE REST;
DROP TABLE CATEGORY;
DROP TABLE LOCATION;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_RNO;
DROP SEQUENCE SEQ_MNNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_RVNO;
DROP SEQUENCE SEQ_FNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_BCNO;
DROP SEQUENCE SEQ_CNO;      -- 카테고리번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_LNO;      -- 로케이션번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_ANO;      -- 알림번호 발생시킬 시퀀스

--------------------------------------------------
------------------  MEMBER TABLE 관련   ------------------   
--------------------------------------------------
CREATE TABLE MEMBER(
    MEM_NO VARCHAR2(20) CONSTRAINT MNO_PK PRIMARY KEY,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PWD VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    ADDRESS VARCHAR2(100),
    MEM_WARNING NUMBER DEFAULT 0 NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MEM_LEVEL CHAR(1) DEFAULT 'U' NOT NULL CHECK (MEM_LEVEL IN('A', 'U')),
    MEM_STATUS CHAR(1) DEFAULT 'Y' NOT NULL CHECK (MEM_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호(ex.M1)';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '거주지';
COMMENT ON COLUMN MEMBER.MEM_WARNING IS '경고횟수';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MEM_LEVEL IS '회원등급(관리자:A, 일반회원:U)';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '회원상태(가입상태:Y, 탈퇴상태:N)';

CREATE SEQUENCE SEQ_MNO
NOCACHE;

--------------------------------------------------
--------------     CATEGORY 관련   ------------------   
--------------------------------------------------
CREATE TABLE CATEGORY(
    CTG_ID VARCHAR2(20) NOT NULL CONSTRAINT CID_PK PRIMARY KEY,
    CTG_NAME VARCHAR2(50)
);

COMMENT ON COLUMN CATEGORY.CTG_ID IS '카테고리ID (ex.C1)';
COMMENT ON COLUMN CATEGORY.CTG_NAME IS '카테고리명';

CREATE SEQUENCE SEQ_CNO
NOCACHE;

--------------------------------------------------
--------------     LOCATION 관련   ------------------   
--------------------------------------------------

CREATE TABLE LOCATION(
    LOCAL_ID VARCHAR2(20) NOT NULL CONSTRAINT LID_PK PRIMARY KEY,
    LOCAL_NAME VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN LOCATION.LOCAL_ID IS '지역ID (ex.L1)';
COMMENT ON COLUMN LOCATION.LOCAL_NAME IS '지역이름';

CREATE SEQUENCE SEQ_LNO
NOCACHE;

--------------------------------------------------
------------------  REST 관련   ------------------   
--------------------------------------------------
CREATE TABLE REST(
    REST_NO VARCHAR2(20) CONSTRAINT RNO_PK PRIMARY KEY,
    REST_LOCAL_ID VARCHAR2(20),
    REST_NAME VARCHAR2(50) NOT NULL,
    CTG_ID VARCHAR2(20) NOT NULL,
    REST_ADDRESS VARCHAR2(60) NOT NULL,
    REST_TEL VARCHAR2(20) CONSTRAINT RESTTEL_UQ UNIQUE,
    REST_X NUMBER,
    REST_Y NUMBER,
    REST_PARKING CHAR(1) CHECK (REST_PARKING IN ('Y','N')),
    REST_GRADE NUMBER,
    REST_TIME VARCHAR2(20), 
    REST_AVG NUMBER, 
    REST_STATUS CHAR(1) DEFAULT 'N' NOT NULL, 
    REST_IMG_URL VARCHAR2(2000) NOT NULL,
    CONSTRAINT RLID_FK FOREIGN KEY(REST_LOCAL_ID) REFERENCES LOCATION(LOCAL_ID),
    CONSTRAINT CTGID_FK FOREIGN KEY(CTG_ID) REFERENCES CATEGORY(CTG_ID)
);

COMMENT ON COLUMN REST.REST_NO IS '식당번호(R1)';
COMMENT ON COLUMN REST.REST_LOCAL_ID IS '지역ID';
COMMENT ON COLUMN REST.REST_NAME IS '식당명';
COMMENT ON COLUMN REST.CTG_ID IS '카테고리ID';
COMMENT ON COLUMN REST.REST_ADDRESS IS '식당주소';
COMMENT ON COLUMN REST.REST_TEL IS '식당전화번호';
COMMENT ON COLUMN REST.REST_X IS '경도';
COMMENT ON COLUMN REST.REST_Y IS '위도';
COMMENT ON COLUMN REST.REST_PARKING IS '주차여부(가능:Y, 불가능:N)';
COMMENT ON COLUMN REST.REST_GRADE IS '식당등급';
COMMENT ON COLUMN REST.REST_TIME IS '영업시간';
COMMENT ON COLUMN REST.REST_AVG IS '총 별점 평균';
COMMENT ON COLUMN REST.REST_STATUS IS '등록상태(등록:Y, 미등록:N)';
COMMENT ON COLUMN REST.REST_IMG_URL IS '대표이미지';

CREATE SEQUENCE SEQ_RNO NOCACHE;

--------------------------------------------------
------------------  MENU 관련   ------------------   
--------------------------------------------------
CREATE TABLE MENU( 
    MENU_NO VARCHAR2(2) CONSTRAINT MNNO_PK PRIMARY KEY, 
    REST_NO VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(50) NOT NULL, 
    MENU_PRICE VARCHAR2(50) NOT NULL, 
    REP_MENU CHAR(1) DEFAULT 'N' CHECK (REP_MENU IN ('Y', 'N')) NOT NULL,
    CONSTRAINT RNO_FK FOREIGN KEY(REST_NO) REFERENCES REST(REST_NO)
);    

COMMENT ON COLUMN MENU.MENU_NO IS '메뉴식별번호(MN1)';
COMMENT ON COLUMN MENU.REST_NO IS '식당번호';
COMMENT ON COLUMN MENU.MENU_NAME IS '메뉴이름';
COMMENT ON COLUMN MENU.MENU_PRICE IS '메뉴가격';
COMMENT ON COLUMN MENU.REP_MENU IS '대표메뉴여부(대표:Y, 대표X:N)';

CREATE SEQUENCE SEQ_MNNO NOCACHE;

--------------------------------------------------
------------------  HEART 관련   ------------------   
--------------------------------------------------
CREATE TABLE HEART(
    REST_NO VARCHAR2(20),
    MEM_NO VARCHAR2(20),
    LIKE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT H_MNO_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
    CONSTRAINT H_RNO_FK FOREIGN KEY(REST_NO) REFERENCES REST(REST_NO),
    CONSTRAINT RMNO_PK PRIMARY KEY(REST_NO, MEM_NO)
);

COMMENT ON COLUMN HEART.REST_NO IS '식당번호';
COMMENT ON COLUMN HEART.MEM_NO IS '회원번호';
COMMENT ON COLUMN HEART.LIKE_DATE IS '찜꽁한날짜';

--------------------------------------------------
------------------  ALERT 관련   ------------------   
--------------------------------------------------
CREATE TABLE ALERT(
    ALERT_NO VARCHAR2(20) NOT NULL PRIMARY KEY,
    MEM_NO VARCHAR2(20) NOT NULL,
    ALERT_CONTENT VARCHAR2(2000) NOT NULL,
    ALERT_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'N' CHECK (STATUS IN('Y','N')),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO)
);
--CREATE TABLE ALERT(
--    ALERT_NO VARCHAR2(20) NOT NULL CONSTRAINT ANO_PK PRIMARY KEY,
--    MEM_NO VARCHAR2(20) NOT NULL,
--    ALERT_CONTENT VARCHAR2(2000) NOT NULL,
--    ALERT_DATE DATE  DEFAULT SYSDATE NOT NULL,
--    STATUS CHAR(1) DEFAULT 'N' CHECK (STATUS IN('Y','N')),
--    CONSTRAINT A_MNO_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO)
--);

COMMENT ON COLUMN ALERT.ALERT_NO IS '알림번호 (ex.A1)';
COMMENT ON COLUMN ALERT.MEM_NO IS '회원번호';
COMMENT ON COLUMN ALERT.ALERT_CONTENT IS '알림내용';
COMMENT ON COLUMN ALERT.ALERT_DATE IS '알림일시';
COMMENT ON COLUMN ALERT.STATUS IS '알림상태값(Y/N)';

CREATE SEQUENCE SEQ_ANO
NOCACHE;

--------------------------------------------------
------------------  REVIEW TABLE 관련   ------------------   
--------------------------------------------------
CREATE TABLE REVIEW(
    REVIEW_NO VARCHAR2(20) CONSTRAINT RVNO_PK PRIMARY KEY,
    REST_NO VARCHAR2(20) NOT NULL,
    REVIEW_WRITER VARCHAR2(20) NOT NULL,
    REVIEW_CONT VARCHAR2(300) NOT NULL,
    REVIEW_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    REVIEW_LIKE NUMBER DEFAULT 0 NOT NULL,
    REVIEW_DISLIKE NUMBER DEFAULT 0 NOT NULL,
    ALERT_NO NUMBER DEFAULT 0 NOT NULL,
    RATE_TASTE NUMBER NOT NULL,
    RATE_PRICE NUMBER NOT NULL,
    RATE_SERVICE NUMBER NOT NULL,
    REVIEW_STATUS CHAR(1) DEFAULT 'Y' NOT NULL CHECK (REVIEW_STATUS IN('Y', 'N')),
    CONSTRAINT RV_RNO_FK FOREIGN KEY (REST_NO) REFERENCES REST(REST_NO),
    CONSTRAINT RV_MNO_FK FOREIGN KEY (REVIEW_WRITER) REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰번호(ex.RV1)';
COMMENT ON COLUMN REVIEW.REST_NO IS '식당번호';
COMMENT ON COLUMN REVIEW.REVIEW_WRITER IS '작성자';
COMMENT ON COLUMN REVIEW.REVIEW_CONT IS '리뷰내용';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '작성일';
COMMENT ON COLUMN REVIEW.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN REVIEW.REVIEW_LIKE IS '추천수';
COMMENT ON COLUMN REVIEW.REVIEW_DISLIKE IS '비추천수';
COMMENT ON COLUMN REVIEW.ALERT_NO IS '신고횟수';
COMMENT ON COLUMN REVIEW.RATE_TASTE IS '맛별점';
COMMENT ON COLUMN REVIEW.RATE_PRICE IS '가격별점';
COMMENT ON COLUMN REVIEW.RATE_SERVICE IS '서비스별점';
COMMENT ON COLUMN REVIEW.REVIEW_STATUS IS '리뷰상태(리뷰 삭제 시, N)';

CREATE SEQUENCE SEQ_RVNO
NOCACHE;

--------------------------------------------------
------------------  BOARD 관련   ------------------   

CREATE TABLE BOARD(
    BOARD_NO VARCHAR2(20) CONSTRAINT BNO_PK PRIMARY KEY,
    REST_ID VARCHAR2(20) NOT NULL,
    BOARD_WRITER VARCHAR2(20) NOT NULL,
    BOARD_TYPE CHAR(1) DEFAULT 'I' CHECK(BOARD_TYPE IN ('I', 'D')) NOT NULL ,
    BOARD_TITLE VARCHAR2(60) NOT NULL,
    BOARD_CONT VARCHAR2(4000) NOT NULL,
    BOARD_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_STATUS CHAR(1) DEFAULT 'Y' NOT NULL CHECK(BOARD_STATUS IN ('Y', 'N')),
    CONSTRAINT B_RNO_FK FOREIGN KEY (REST_ID) REFERENCES REST(REST_NO),
    CONSTRAINT B_MNO_FK FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호 (ex.B1)';
COMMENT ON COLUMN BOARD.REST_ID IS '식당번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시글유형 (등록요청:I, 삭제요청:D)';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글작성일';
COMMENT ON COLUMN BOARD.BOARD_STATUS IS '게시글상태 (등록상태:Y, 삭제상태:N)';

CREATE SEQUENCE SEQ_BNO NOCACHE;

--------------------------------------------------
------------------  BOARD_COMMENT관련   ------------------   
--------------------------------------------------
CREATE TABLE BOARD_COMMENT(
    COM_NO VARCHAR2(20) CONSTRAINT BCNO_PK PRIMARY KEY, 
    BOARD_NO VARCHAR2(20) NOT NULL UNIQUE,
    COM_WRITER VARCHAR2(20) NOT NULL,
    COM_CONT VARCHAR2(500) NOT NULL,
    COM_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT BC_MNO_FK FOREIGN KEY (COM_WRITER) REFERENCES MEMBER(MEM_NO),
    CONSTRAINT BC_BNO_FK FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

COMMENT ON COLUMN BOARD_COMMENT.COM_NO IS '댓글번호(ex.BC1)';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD_COMMENT.COM_WRITER IS '작성자 (ex.M1)';
COMMENT ON COLUMN BOARD_COMMENT.COM_CONT IS '댓글내용';
COMMENT ON COLUMN BOARD_COMMENT.COM_DATE IS '댓글작성일';

CREATE SEQUENCE SEQ_BCNO NOCACHE;

--------------------------------------------------
------------------  IMG_FILE관련   ------------------   
--------------------------------------------------
--CREATE TABLE IMG_FILE(
--    IMG_FILE_NO VARCHAR2(20) CONSTRAINT FNO_PK PRIMARY KEY,
--    REF_NO NUMBER NOT NULL,
--    IMG_ORIGIN_NAME VARCHAR2(255),
--    IMG_CHANGE_NAME VARCHAR2(255),
--    IMG_FILE_PATH VARCHAR2(1000) NOT NULL,
--    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
--    IMG_STATUS VARCHAR2(10) NOT NULL
--);

CREATE TABLE IMG_FILE(
    IMG_FILE_NO VARCHAR2(20) PRIMARY KEY,
    REF_NO NUMBER NOT NULL,
    IMG_ORIGIN_NAME VARCHAR2(255),
    IMG_CHANGE_NAME VARCHAR2(255),
    IMG_FILE_PATH VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    IMG_STATUS VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN IMG_FILE.IMG_FILE_NO IS '파일번호(ex.F1)';
COMMENT ON COLUMN IMG_FILE.REF_NO IS '참조게시글번호';
COMMENT ON COLUMN IMG_FILE.IMG_ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN IMG_FILE.IMG_CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN IMG_FILE.IMG_FILE_PATH IS '파일저장경로';
COMMENT ON COLUMN IMG_FILE.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN IMG_FILE.IMG_STATUS IS '파일상태';

CREATE SEQUENCE SEQ_FNO
NOCACHE;

COMMIT;